# Generated by Django 4.1.13 on 2024-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_researchpaper_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='banner_url',
            field=models.URLField(blank=True),
        ),
    ]
