# Generated by Django 4.1.13 on 2024-08-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_researchpaper_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='your_upload_directory/'),
        ),
    ]
